spring.application.name=ServiceHub

spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/servicehub
spring.datasource.username=servicehub
spring.datasource.password=servicehub

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true